name: Build and Deploy Code

on: [push, pull_request]

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
          - name: pulling git repository
            uses: actions/checkout@v2
          - name: say hi to sebas
            run: echo "hi sebas"


# on: [push, pull_request]
# on: 
#     push:
#         branches: #["main"] #["main", "other branches"]
#           - "main" 

